### ISSUE TITLE
Who can comprise a cohort team?

### ISSUE THREAD

**Issue by cclatterbuck** [CAWaterBoardDataCenter/swrcb-openscapes#12]
Add to "What makes a good Openscapes team": highlight that applicants create their own teams and are not constrained by their relationship on, say, the org chart. Teams can be created across RDOs, and the implementation team does not have a quota for teams coming from certain RDOs. 

Consider adding that Openscapes shouldn't be used to address a single "work project" but for colleagues that regularly work together, whatever that looks like for that team.

**Comment by AHolder1** [comment]
@cclatterbuck Does content on [this page](https://cawaterboarddatacenter.github.io/swrcb-openscapes/about_at_swrcb/team_guidance.html) address this? or is there more we should add?

**Comment by cclatterbuck** [comment]
Just added some guidance on who can comprise a team for the 2023 cohort -- closing the issue but re-open if there are other items to address.
