### ISSUE TITLE
2023 Pre-cohort Planning and Engagement (Jul-mid Aug)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#17]
To do list:
_Team communications_
- [x] Jul 3-10: Review application for team nominations
- [x] Jul 3-10: Draft email language templates (@AHolder1 )
- [x]  Jul 3-10: Review email language templates (@cclatterbuck , @DevanBurke , @tures23 )
- [x] Jul 10-17: Email notifications to teams @AHolder1 
- [x] Jul 17-21: Email confirmed teams; schedule 1:1 Intro Calls (Aug 8-11); send all cohort calendar invites
- [x] Aug 1-10: Email cohort call reminder + action items to complete before start of Cohort following week (Aug 16 9:30-11:30 am)

_Other Prep_
- [x] Work with the external and internal Openscapes communities to identify, invite, and coordinate guest teachers to present topics during Cohort Calls. 
- [x] Set up all necessary documentation (e.g., Cohort sharing folders, Cohort Call agendas, GitHub repositories, lesson plans and presentations).
- [x] Update website (remove application info, add cohort details)
- [x] Update Cohort Call issues (tag names next to roles, confirm to do list - [Call 1](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/18), [Call 2](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/21), [Call 3](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/22), [Call 4](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/23), [Call 5](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/24), [2-month check-in](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/25))
- [x] Invite all incoming team members to the internal Water Boards Openscapes Microsoft Team so they can introduce themselves to the Water Boards Openscapes Community.
- [x] Invite and onboard identified Openscapes mentors to the Openscapes Team, as appropriate.

**Comment by cclatterbuck** [comment]
Kyber setup notes:

- Follow [installation](https://github.com/Openscapes/kyber#installation) and [configuration](https://github.com/Openscapes/kyber#configuration) instructions in the README, but you don’t need to set up Git credentials if you have already set up a PAT for R/Github (e.g., if you've pushed to the swrcb-openscapes repository before). 
- You might need to update and/or remove packages to complete installation & configuration. 
- Kyber requires access to a Google account via Tidyverse API to write and read Google docs & sheets. Allow access to complete work in Kyber, then remove access once no longer needed on Google account.
