### ISSUE TITLE
2024 Fall Pre-cohort Planning and Engagement (Jul)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#40]
To do list:
_Team communications_
- [x] Jul 1-3 - Review application for team nominations
- [x] Jul 1-3 - Review email language templates
- [x] Jul 1-3 - Email notifications to teams 
- [x] Jul 8-12 - Email confirmed teams; schedule Team 1:1 Calls (Jul 22-26); send all cohort calendar invites (cohort calls, co-working, 2 month check-in)
- [x] Jul 15-19 - Create Team 1:1 Agendas
- [x] Jul 22-26 - Hold Team 1:1 Calls
- [x] Jul 29-Aug 2 - Email cohort call reminder + action items to complete before start of Cohort following week (Aug 7)
- [x] Jul 29-Aug 2 - Invite all team members to the MS Meeting Materials Folder + internal Water Boards Openscapes Microsoft Team so they can introduce themselves to the Water Boards Openscapes Community.

_Other Prep_
- [x] Work with the external and internal Openscapes communities to identify, invite, and coordinate guest teachers to present topics during Cohort Calls. 
- [x] Update website (add cohort details)
- [x] Create cohort GitHub team ([Kyber](https://github.com/Openscapes/kyber) + Openscapes Staff)
- [x] Update Cohort Call issues (tag mentor names next to roles, confirm to do list
  - [x] [Call 1](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/41)
  - [x] [Call 2](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/42)
  - [x] [Call 3](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/43)
  - [x] [Call 4](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/44)
  - [ ] [Call 5](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/45)
  - [x] [2-month check-in](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/46))

**Comment by vlzimmer** [comment]
Looks good @AHolder1

**Comment by dl-cantrell** [comment]
@vlzimmer hiiiiii
