### ISSUE TITLE
2024 Fall Cohort Process - Call 1 (Aug 7)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#41]
_To do list_

- [x] 2+ weeks prior to call: confirm logistics with guest speaker; schedule prep call if needed 
- [x] 1 week prior to call: Finalize lesson plan/slides
- [x] 1 week prior to call: Email reminder/confirmation to guest speakers (if any)
- [x] By Fri after call: Thank you email to guest speaker
- [x] By Fri after call: Initiate guest speaker honorarium
- [x] By Fri after call: Download, format, post call recording
- [x] By Fri after call: Draft Digest, send for review @dl-cantrell 
- [x] By Tues following call: Review digest @AHolder1 @tures23 
- [x] By  Wed following call: Send digest @dl-cantrell

**Comment by AHolder1** [comment]
Good morning @dl-cantrell ! Please tag @tures23 and I here when you've completed the draft digest for Call 1. As a reminder, the template is in the Mentor Materials folder. Let me know if you have any questions! :)

**Comment by dl-cantrell** [comment]
@AHolder1 and @tures23 , I've updated the draft digest for Call 1! Do I email it to everyone as well? Or do you two send it out?

**Comment by tures23** [comment]
Howdy! Fantastic digest @dl-cantrell :) no comments from me.

**Comment by dl-cantrell** [comment]
@AHolder1 and @tures23 - posted the digest to the cohort channel :)

**Comment by AHolder1** [comment]
AWESEOME! It looks great - I'll officially close this issue. Go team!
