### ISSUE TITLE
2024 Fall Cohort Process - Call 2 (Aug 21)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#42]
_To do list_

- [x] 2+ weeks prior to call: confirm logistics with guest speaker; schedule prep call if needed - NA
- [x] 1 week prior to call: Finalize lesson plan/slides
- [x] 1 week prior to call: Email reminder/confirmation to guest speakers (if any) - NA
- [x] By Fri after call: Thank you email to guest speaker - NA
- [x] By Fri after call: Initiate guest speaker honorarium - NA
- [x] By Fri after call: Download, format, post call recording
- [x] By Fri after call: Draft Digest, send for review @esuglia 
- [x] By Tues following call: Review digest @AHolder1 @tures23 
- [x] By  Wed following call: Send digest @esuglia

**Comment by AHolder1** [comment]
Hi @tures23 can you review the draft digest that @esuglia put together and then tag me in for review here? Thanks!

**Comment by tures23** [comment]
Happy Friyay! digest #2 looks wonderful, love the notes from the shared agenda!! way to go @esuglia :) @AHolder1 tag you it for review

**Comment by AHolder1** [comment]
@esuglia I think the digest is ready to go! +100 to the notes you included from the agenda! 
I made a couple of formatting edits and added a pacman rule graphic. 

For now, let's post in the [Fall Cohort's MS Teams Channel](https://teams.microsoft.com/l/channel/19%3Aeb0b388c31e54091beda55402d9cfd85%40thread.tacv2/%5B2024-Fall-Cohort%5D?groupId=d20bd7eb-287d-4c0e-8200-be28810f6112&tenantId=fe186a25-7d49-41e6-9941-05d2281d36c1) - [like we did last week](https://teams.microsoft.com/l/message/19:eb0b388c31e54091beda55402d9cfd85@thread.tacv2/1723493199025?tenantId=fe186a25-7d49-41e6-9941-05d2281d36c1&groupId=d20bd7eb-287d-4c0e-8200-be28810f6112&parentMessageId=1723493199025&teamName=WB-OIMA-Openscapes&channelName=%5B2024-Fall-Cohort%5D&createdTime=1723493199025). 

We will make it an issue during the next mentors seaside chat so you can demo and other mentors can get more comfortable with submitting issues. Go team!!
