### ISSUE TITLE
2024 Fall Cohort Process - Call 3 (Sep 4)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#43]
_To do list_

- [x]  2+ weeks prior to call: confirm & coordinate logistics with guest speaker; schedule prep call if needed
- [x] 1 week prior to call: Finalize lesson plan/slides
- [x] 1 week prior to call: Email reminder/confirmation to guest speakers (if any)
- [x] Add team members to GitHub Team; confirm notification acceptance ([Kyber](https://github.com/Openscapes/kyber) + Openscapes Staff)
- [x] By Fri after call: Thank you email to guest speaker
- [x] By Fri after call: Initiate guest speaker honorarium
- [x] By Fri after call: Download, format, post call recording
- [x] #51 @vlzimmer 
- [x] By Tues following call: Review digest @AHolder1 @tures23 
- [x] By  Wed following call: Send digest @vlzimmer

**Comment by vlzimmer** [comment]
Ok all - I finished a draft of the digest!

**Comment by AHolder1** [comment]
AWESOME! @tures23 can you please take the first round of review and tag me back in when you're done? I won't be able to take a look until Fri. Thankssssss!

**Comment by tures23** [comment]
wonderful digest @vlzimmer  ! I love the pathway reminder at the end :) @AHolder1 please review if you haven't already. thank you!!

**Comment by AHolder1** [comment]
The digest looks great @vlzimmer ! Send awayyy! 
Some reminders: 

- you may need to download the images and then upload them (simple copy paste might not work) 
- Be sure to @ the cohort's team (2024-swrcb-fall-cohort) at the top of the issue so that folks get an email when the digest is posted.
