### ISSUE TITLE
2024 Fall Cohort Process - Call 5 (Oct 2)

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#45]
_To do list_

- [x] 1 week prior to call: Finalize lesson plan/slides
- [x] By Fri after call: Download, format, post call recording
- [x] By Fri after call: Draft Digest, send for review @madiboynton 
- [x] By Tues following call: Review digest @AHolder1 @tures23 
- [x] By  Wed following call: Send digest @madiboynton

**Comment by AHolder1** [comment]
Hi-ya @madiboynton ! Let me and @tures23 know when you've got the draft digest (doc in our Mentor Materials Folder) ready for our review. If you want to jump on a call to co-work before posting the GitHub Issue, we can make time for that too! :)

**Comment by madiboynton** [comment]
@AHolder1 whoops -- thank you for the reminder! I will draft the digest and put it in the folder today or tomorrow.

**Comment by madiboynton** [comment]
@AHolder1 @tures23 Done drafting! [https://cawaterboards-my.sharepoint.com/:w:/r/personal/anna_holder_waterboards_ca_gov/_layouts/15/Doc.aspx?sourcedoc=%7BC8EC2749-38E8-4849-A84D-C16423878FB4%7D&file=DRAFT%20Digests.docx&action=default&mobileredirect=true](url)

**Comment by tures23** [comment]
@madiboynton marvelous digest! added the Teams link for the 2 month check in, not sure the link makes sense so take a look :)  tag to you @AHolder1

**Comment by AHolder1** [comment]
Everything looks great @madiboynton ! Go ahead and create the Issue and @ the team to send whenever you're ready this week. If you want to jump on a call and co-work to get it done, let me know. :)
