### ISSUE TITLE
Update Presentations and Media Page

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swrcb-openscapes#5]

**Comment by cclatterbuck** [comment]
I'd like to discuss what we have to populate this page. My idea is to make this a broader "resources" page to include presentations as a subheading with a couple of our internal presentations to groups. Documents could be another subheading, where we could include access to the implementation strategy.

**Comment by AHolder1** [comment]
I like it! Let's confirm the plan and maybe even make the changes during an upcoming co-working session!
